"""
Builds the V3 pixel-font assets from Fusion Pixel Font (12px, proportional, zh_hant; SIL OFL 1.1):
https://github.com/TakWolf/fusion-pixel-font/releases

  1. src/assets/fonts/fusion-pixel-12.woff2   the font, subset to the characters the game uses
  2. src/rendering/pixelGlyphs.ts           the piece, river and stamp characters as SVG paths, each centred
                                            on its visual centre, so every piece's character sits
                                            exactly in the middle of its disc at any size

Usage (needs fonttools and brotli):
  python3 scripts/pixel-font.py path/to/fusion-pixel-12px-proportional-zh_hant.ttf.woff2
"""

import glob
import sys
from pathlib import Path

from fontTools import subset
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.statisticsPen import StatisticsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
# Pieces, the river, and the verdict stamps shown when a game ends.
GLYPHS = '帥將仕士相象傌馬俥車炮砲兵卒楚河漢界勝負和'
# How far the centre moves from the ink's bounding box toward its centre of mass:
# a little, so heavy strokes on one side do not make a character look off-centre.
MASS = 0.3


def used_characters() -> str:
    chars = set(chr(c) for c in range(0x20, 0x7F)) | set(chr(c) for c in range(0xA0, 0x100))
    chars |= set('·—–‘’“”…•、。，：；！？「」『』（）《》〈〉')
    for path in glob.glob(str(ROOT / 'src/**/*.ts*'), recursive=True) + glob.glob(str(ROOT / 'src/**/*.css'), recursive=True):
        chars |= {c for c in Path(path).read_text(encoding='utf8') if ord(c) > 0x7F}
    return ''.join(sorted(chars))


def build_font(source: str) -> None:
    out = ROOT / 'src/assets/fonts/fusion-pixel-12.woff2'
    out.parent.mkdir(parents=True, exist_ok=True)
    options = subset.Options()
    options.flavor = 'woff2'
    options.layout_features = ['*']
    options.name_IDs = ['*']
    font = TTFont(source)
    sub = subset.Subsetter(options)
    sub.populate(text=used_characters())
    sub.subset(font)
    font.flavor = 'woff2'
    font.save(out)
    print(f'{out.relative_to(ROOT)}: {out.stat().st_size // 1024} KB')


def build_glyphs(source: str) -> None:
    font = TTFont(source)
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    unit = font['head'].unitsPerEm / 12  # font units per pixel of the 12px design
    lines = []
    for ch in GLYPHS:
        g = glyphs[cmap[ord(ch)]]
        bounds = BoundsPen(glyphs)
        g.draw(bounds)
        x0, y0, x1, y1 = bounds.bounds
        stats = StatisticsPen(glyphs)
        g.draw(stats)
        cx = (x0 + x1) / 2 * (1 - MASS) + stats.meanX * MASS
        cy = (y0 + y1) / 2 * (1 - MASS) + stats.meanY * MASS
        # To font pixels, centred on the visual centre, y pointing down (SVG).
        pen = SVGPathPen(glyphs, ntos=lambda v: f'{round(v, 3):g}')
        g.draw(TransformPen(pen, (1 / unit, 0, 0, -1 / unit, -cx / unit, cy / unit)))
        lines.append(f"  '{ch}': '{pen.getCommands()}',")
    out = ROOT / 'src/rendering/pixelGlyphs.ts'
    out.write_text(
        '/**\n'
        ' * Pixel glyphs for the V3 pieces, river and verdict stamps, from Fusion Pixel Font (12px, SIL OFL 1.1).\n'
        ' * Generated by scripts/pixel-font.py; do not edit by hand.\n'
        ' *\n'
        ' * Each path is in font pixels (the design is 12 px to the em), centred on the\n'
        " * character's visual centre: its ink box, nudged toward its centre of mass.\n"
        ' */\n'
        'export const GLYPH_EM = 12\n\n'
        'export const PIXEL_GLYPHS: Record<string, string> = {\n' + '\n'.join(lines) + '\n}\n',
        encoding='utf8',
    )
    print(f'{out.relative_to(ROOT)}: {len(GLYPHS)} glyphs')


if __name__ == '__main__':
    build_font(sys.argv[1])
    build_glyphs(sys.argv[1])
